"""
Django settings for muoj project.
Generated by 'django-admin startproject' using Django 3.1.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import environ
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

env = environ.Env()
environ.Env.read_env((BASE_DIR / '.env').as_posix())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

DEBUG = False

#Hosting in heroku
ALLOWED_HOSTS = ['muoj.herokuapp.com/', 'localhost']

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party Apps
    'ckeditor',
    'crispy_forms',
    'rest_framework',
    'django_celery_results',
    'django_celery_beat',
    'debug_toolbar',
    'channels',
    'channels_redis',
    'django_json_widget',

    # My Apps
    'accounts.apps.AccountsConfig',
    'blog.apps.BlogConfig',
    'contest.apps.ContestConfig',
    'core.apps.CoreConfig',
    'problemset.apps.ProblemsetConfig',
    'training.apps.TrainingConfig',
    'dashboard.apps.DashboardConfig',
    'channel.apps.ChannelConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'core.middleware.TimezoneMiddleware'
]

ROOT_URLCONF = 'muoj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'muoj.wsgi.application'
ASGI_APPLICATION = "muoj.asgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# REST Framework Configs
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': None
}

# Logging Configs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}]:{levelname}:{message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %H:%M:%S'
        }
    },

    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'debug.log',
            'maxBytes': 1024 * 1024 * 100,  # 100 MB
            'backupCount': 5,
            'formatter': 'verbose'
        }
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False
        }
    }
}

# CKEditor
CKEDITOR_CONFIGS = {
    'default': {
        'height': '300',
        'width': '100%',
        'toolbarCanCollapse': True,
        'toolbarStartupExpanded': False,
        'codeSnippet_theme': 'railscasts',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar': [
            ["Format", "Preview", "Bold", "Italic", "Underline", "Strike", "SpellChecker"],
            ['NumberedList', 'BulletedList', "Indent", "Outdent", 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ["Image", "Table", "Link", "Unlink", "Anchor", "SectionLink", "Subscript", "Superscript"],
            ['Undo', 'Redo'],
            ['Styles', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ["Source"],
            ["Maximize", "CodeSnippet"]
        ],
        'extraPlugins': ','.join([
            'codesnippet',
            'widget',
            'dialog',
        ])
    },
}

# Messages Framework tags customization
MESSAGE_TAGS = {
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

# Celery Configuration Options
CELERY_TIMEZONE = "Asia/Dhaka"
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Channels Config
CHANNEL_LAYERS = {
    "additional": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        }
    },
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Other configs
CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
AUTH_USER_MODEL = 'accounts.User'


# JAZZMIN Configs
JAZZMIN_SETTINGS = {
    # "show_ui_builder": True,

    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "MUOJ Admin",

    # Title on the brand, and login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "MUOJ Admin Panel",

    # square logo to use for your site, must be present in static files, used for favicon and brand on top left
    # "site_logo": "books/img/logo.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to MU Online Judge",

    # Copyright on the footer
    "copyright": "MUOJ Team",

    # Field name on user model that contains avatar image
    "user_avatar": None,

    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"app": "contest"},
        # {"model": "problemset.Problem"}
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "View Site", "url": "/", "icon": "fa fa-eye"},
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['django_celery_results', 'django_celery_beat'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free
    # for a list of icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "auth.Permission": "fas fa-lock",
        "accounts.user": "fas fa-users",
        "accounts.Profile": "fas fa-user",
        "blog.Blog": "fas fa-book",
        "blog.Comment": "fas fa-comment",
        "channel.Channel": "fas fa-wallet",
        "channel.Message": "fas fa-comment-dots",
        "contest.Contest": "fas fa-poll",
        "contest.Announcement": "fas fa-bullhorn",
        "core.Constant": "fas fa-adjust",
        "problemset.Problem": "fas fa-question-circle",
        "problemset.Language": "fas fa-language",
        "problemset.Submission": "fas fa-chalkboard",
        "problemset.Clarification": "fas fa-broom",
        "problemset.TestCase": "fas fa-vial",
        "training.Tutorial": "fas fa-graduation-cap",
    },

    "custom_css": "jazzmin/css/main.css",
    "custom_js": "jazzmin/js/main.js",

}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-outline-danger",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": False
}
